define(function (require) {
    return  [
                ['niña', 'se', 'temprano.', 'La', 'acuesta'],
                ['árbol', 'copa', 'Ese', 'muy', 'tiene', 'frondosa.', 'una'],
                ['rota.', 'tiene', 'águila', 'el', 'El', 'ala'],
                ['una', 'A', 'regalaron', 'mi', 'hermana', 'le', 'muñeca.'],
                ['todos', 'Juan', 'días.', 'corre', 'los'],
                ['flores', 'mamá.', 'Mi', 'para', 'hermano', 'corta', 'mi'],
                ['agua', ',', 'que', 'El', 'pediste', 'caliente.', 'está'],
                ['llueve', 'y', 'el', 'sol.', 'Primero', 'luego', 'sale'],
                ['sopla', 'Patricia', 'velas.', 'las'],
                ['por', 'mañana.', 'Juana', 'fue', 'la', 'se'],
                ['ahorró', 'vacaciones.', 'Miguel', 'dinero', 'las', 'mucho', 'en'],
                ['delicioso.', 'estaba', 'postre', 'El'],
                ['están', 'futbol.', 'Los', 'jugando', 'niños'],
                ['reunión.', 'Felipe', 'a', 'llegó', 'la', 'temprano'],
                ['son', 'Los', 'amigos.', 'perros', 'fieles'],
                ['muy', 'Marta', 'alegre.', 'está'],
                ['jugando', 'perro.', 'Los', 'con', 'niños', 'están', 'el'],
                ['ciudad.', 'en', 'Llueve', 'mi'],
                ['mucho', 'Tengo', 'frío.'],
                ['muchas', 'come', 'Teresa', 'verduras.'],
                ['juega', 'María', 'el', 'perro.', 'con'],
                ['estaba', 'alegre.', 'gatito', 'El'],
                ['calle.', 'Los', 'juegan', 'la', 'niños', 'en'],
                ['hay', 'la', 'En', 'peine.', 'un', 'tienda'],
                ['grandes.', 'están', 'verdes', 'árboles', 'y', 'Los'],
                ['montaña.', 'está', 'la', 'La', 'en', 'casa'],
                ['La', 'de', 'felicidad.', 'niña', 'salta'],
                ['riega', 'El', 'las', 'jardinero', 'plantas.'],
                ['las', 'El', 'marca', 'reloj', 'horas.'],
                ['caliente.', 'niño', 'leche', 'El', 'bebe'],
                ['compra', 'el', 'Pedro', 'verduras', 'en', 'mercado.'],
                ['bicicleta.', 'en', 'salió', 'Bertha'],
                ['hombre', 'es', 'Raúl', 'un', 'alto.'],
                ['está', 'El', 'cansado.', 'atleta'],
                ['de', 'Juan', 'amigo', 'José.', 'es'],
                ['blanco.', 'Rita', 'vestido', 'un', 'tiene'],
                ['la', 'toca', 'Julio', 'guitarra.'],
                ['granja', 'muchos', 'En', 'hay', 'animales.', 'la'],
                ['ruidosa.', 'La', 'grande', 'ciudad', 'es', 'y'],
                ['a', 'las', 'Mirna', 'juega', 'muñecas.'],
                ['cuida', 'El', 'la', 'Perro', 'casa.'],
                ['gato', 'ratón', 'come', 'y', 'El', 'queso', 'observa.', 'lo', 'el'],
                ['compró', 'pantalón.', 'una', 'Carlos', 'un', 'y', 'camisa'],
                ['está', 'gato', 'Ese', 'durmiendo.'],
                ['libros.', 'profesor', 'mesa', 'muchos', 'La', 'tiene', 'del'],
                ['Doris', 'negro.', 'tiene', 'pelo', 'el'],
                ['color', 'La', 'es', 'camisa', 'de', 'negro.'],
                ['tiene', 'perro.', 'Juana', 'un'],
                ['bebe', 'María', 'caramelos', 'come', 'y', 'agua.'],
                ['está', 'cocina.', 'La', 'en', 'botella', 'la'],
                ['alimenta', 'gato.', 'Jeni', 'al'],
                ['iremos', 'Mañana', 'parque.', 'al'],
                ['realiza', 'un', 'Juan', 'dibujo.'],
                ['perro', 'Isabel', 'mascota.', 'tiene', 'un', 'de'],
                ['iremos', 'Mañana', 'parque.', 'al'],
                ['iremos', 'Mañana', 'paseo', 'de', 'zoológico.', 'al'],
                ['hace', 'cena.', 'Mamá', 'la'],
                ['usan', 'Las', 'vestido.', 'niñas'],
                ['El', 'es', 'televisor', 'grande.', 'muy'],
                ['escribió', 'poesía.', 'Juan', 'hermosa', 'una'],
                ['percigue', 'al', 'El', 'ratón.', 'gato'],
                ['Gabriela', 'bonita.', 'una', 'es', 'niña'],
                ['carro', 'cuatro', 'El', 'llantas.', 'tiene'],
                ['estrellas', 'en', 'cielo.', 'Las', 'el', 'están'],
                ['caminos.', 'por', 'La', 'llevó', 'luna', 'sus', 'me'],
                ['niños', 'perro.', 'Los', 'juegan', 'el', 'con'],
                ['Los', 'parte', 'naturaleza.', 'árboles', 'la', 'de', 'son'],
                ['viaja', 'en', 'barco.', 'Camila', 'el'],
                ['Nicaragua.', 'capital', 'de', 'es', 'la', 'Managua'],
                ['Uruguay', 'La', 'es', 'Montevideo.', 'capital', 'de'],
                ['capital', 'es', 'Madrid', 'la', 'España.', 'de'],
                ['capital', 'Roma', 'de', 'Italia.'],
                ['tiene', 'Moscú.', 'Rusia', 'capital', 'de', 'a'],
                ['crecerá', 'lágrimas.', 'mar', 'con', 'El', 'mis'],
                ['alegría', 'construir', 'nuevo.', 'con', 'lo', 'la', 'Estamos', 'de'],
                ['es', 'Bogotá', 'Colombia', 'capital', 'la', 'de'],
                ['pastel', 'está', 'El', 'delicioso.'],
                ['cinco', 'dedos', 'Tengo', 'la', 'en', 'mano.'],
                ['respeto', 'basa', 'no', 'en', 'se', 'el', 'miedo.', 'El'],
                ['planchaba', 'con', 'una', 'Pancha', 'plancha.'],
                ['árbol', 'todos', 'leña.', 'Del', 'caído', 'hacen'],
                ['y', 'sacarán', 'Cría', 'te', 'ojos.', 'los', 'cuervos'],
                ['inquieto.', 'cabrito', 'Pony', 'un', 'es'],
                ['y', 'nueva.', 'cuenta', 'Borrón'],
                ['El', 'por', 'boca', 'pez', 'la', 'muere.'],
                ['es', 'niña', 'Anita', 'una', 'feliz.'],
                ['insectos', 'mariposas', 'Las', 'son', 'hermosos.'],
                ['Dios', 'y', 'el', 'dando.', 'A', 'rogando', 'con', 'mazo'],
                ['morral.', 'Un', 'su', 'mozo', 'y', 'trae', 'herramientas', 'por', 'sus', 'un', 'sendero'],
                ['teclado', 'clave', 'el', 'Está', 'sonoro.', 'mudo', 'su', 'de']
            ];
});
